version: "3.8"
services:
  mongodb:
    image: mongo
    volumes:
      - mongodbdata:/data/db
    env_file:
      - ./env/mongo.env
    container_name: mongodb
  backend:
    build: ./backend
    volumes:
      - ./products-api/src:/app/src
    ports:
      - 5002:5002
    # env_file:
    #   - ./env/backend.env
    depends_on:
      - mongodb
    container_name: backend
  frontend:
    build: ./frontend
    ports:
      - 80:80
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  mongodbdata:
