FROM node:18-alpine as builder
# make the directory where the project files will be stored
RUN mkdir -p /app

WORKDIR /usr/app

COPY package*.json .

RUN npm install

COPY . .

RUN npm run build

FROM nginx

RUN rm -rf /usr/share/nginx/html/* && rm -rf /etc/nginx/conf.d/default.conf 

COPY --from=builder app/.next /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"] && npm start